# Generated by Django 5.0.3 on 2024-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_keyfeature_remove_product_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.ManyToManyField(related_name='products', to='product.keyfeature'),
        ),
        migrations.DeleteModel(
            name='ProductKeyFeature',
        ),
    ]
