# Generated by Django 5.0.3 on 2024-03-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_keyfeature_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyfeature',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
