# Generated by Django 5.0.3 on 2025-01-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False),
        ),
    ]
