# Generated by Django 5.0.3 on 2025-01-24 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_remove_product_key_features"),
        ("vendors", "0003_alter_vendor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="vendors.vendor",
            ),
            preserve_default=False,
        ),
    ]
