# Generated by Django 5.0.3 on 2025-01-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="store_name",
            field=models.CharField(default=None, max_length=70),
        ),
    ]
