# Generated by Django 5.0.3 on 2025-01-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_store_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ("store_name",)},
        ),
    ]
