# Generated by Django 5.0.3 on 2025-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
