# Generated by Django 5.0.3 on 2025-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_vendor_approved"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="store_name",
            field=models.CharField(max_length=70),
        ),
    ]
