# Generated by Django 5.0.3 on 2024-04-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_token',
            new_name='paystack_token',
        ),
    ]
