# Generated by Django 5.0.3 on 2024-04-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_paystack_token_order_stripe_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user_email',
        ),
    ]
