# Generated by Django 5.0.3 on 2024-04-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_email_order_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='email',
        ),
    ]
