# Generated by Django 5.0.3 on 2025-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="method",
            field=models.CharField(
                choices=[("card", "card"), ("cash", "cash")],
                default="card",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
