# Generated by Django 5.0.3 on 2025-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_method_alter_order_stripe_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="stripe_token",
            new_name="stripe_payment_id",
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="eur", max_length=3),
        ),
    ]
